### ISSUE TITLE
[L10N][Japanese]: Overlocalized Edge Inspect extension on Japanese OS.

### ISSUE THREAD

**Issue by julieyuan** [edge-code/edge-inspect-extension#11]
Steps:
1. Launch Edge Code.
2. Click Edge Inspect extension on the top right of Edge Code.

Results:
Edge Inspect extension is over localized.

Expected:
As Edge Code will not release Japanese language so far,  All the UI should stay in English on Japanese OS. So Edge Inspect extension should not be localized.

ENV: MAC 10.7.5 Japanese OS
Build: 0.95.0-359081200

Snapshots:
Please refer to snapshot for details:
![2013-07-22 10 32 16 pm](https://f.cloud.github.com/assets/4251563/839872/24b00a4c-f35c-11e2-9e68-e8949b9de3b6.png)

**Comment by bchintx** [comment]
This fix will be available in Edge Code after the next Brackets merge
https://git.corp.adobe.com/edge/edge-code/pull/190

**Comment by bchintx** [comment]
The Brackets changes have been merged into Edge Code master branch.  The fix should now be available in the next Edge Code build.

@julieyuan Please confirm and close this issue when you check the next Edge Code build.  Thanks

**Comment by julieyuan** [comment]
Fixed in build 0.95.0-359081293. Please refer to snapshot:
![2013-07-25 7 08 29 pm](https://f.cloud.github.com/assets/4251563/860150/36df38a2-f599-11e2-8096-7dc5aca02a84.png)
