### ISSUE TITLE
Add Extension to brackets extension registry

### ISSUE THREAD

**Issue by WebsiteDeveloper** [edge-code/edge-inspect-extension#18]
The extension should be avaliable in the brackets extension registry
https://brackets-registry.aboutweb.com/
so it is much more easy to find.

**Comment by iwehrman** [comment]
Good idea! Closing as fixed: 
![em](http://f.cl.ly/items/1u3d2S371j0u141W3D10/Screen%20Shot%202013-08-05%20at%2011.02.58%20AM.png)
