### ISSUE TITLE
[Core][Getting started dialog]: The  Need help link on Getting started dialog is broken.

### ISSUE THREAD

**Issue by julieyuan** [edge-code/edge-inspect-extension#29]
Steps:
1. Install Ege Code and launch it.
2. Click the inspect extension icon on the top right, it will pop up Edge Inspect dialog.
If not, it can be visible by clicking Edge Insepect CC > Getting started...
3. Click the link "Need help? Ask the Adobe Community..." on the left bottom of this dialog.

Result:
Nothing happened.

Expected:
It should redirect to related page.

Notes:
It works for Edge Code preview 6 release build.

ENV: MAC10.7 and Win8.1 English OS
Build: 0.96.0-359083025

Snapshots:
Please refer to snapshots for details.
![disabled link](https://f.cloud.github.com/assets/4251563/1312777/21c31590-3245-11e3-9e82-14ad823e1b21.png)
Preview 6 release build for reference:
![gm build](https://f.cloud.github.com/assets/4251563/1312779/2554e620-3245-11e3-8d48-63332ed4aa57.png)

**Comment by bchintx** [comment]
Good catch, @julieyuan .  This should be fixed in the next EdgeCode build -- ie. it _might_ be in 0.96.0-359083026, but, if not, it'll be in the next one.

**Comment by bchintx** [comment]
Oh, wait.  I was looking in the wrong place.  This isn't fixed yet.

**Comment by bchintx** [comment]
Fixed with pull request #32.  @julieyuan Can you please confirm the fix and close this issue using the latest Edge Code Preview 7 release?

**Comment by julieyuan** [comment]
Thanks @bchintx ! It is fixed in latest build 0.97.0-359084115. So closing it. Here is snapshot for reference: 
![screen shot 2013-11-20 at 6 01 31 pm](https://f.cloud.github.com/assets/4251563/1588480/3338812a-5252-11e3-9d93-cf792f88dc8c.png)
