### ISSUE TITLE
Provide some Guidance About How to Use Edge Inspect

### ISSUE THREAD

**Issue by iwehrman** [edge-code/edge-inspect-extension#3]
It would be good if we had some helpful information about how to use Edge Inspect.

Potentially on first click of the icon we could bring up a pop-up that describes how to get it working. Similar to the Edge Web Fonts pop up.

(See previous internal discussion [here](https://git.corp.adobe.com/edge/edge-code-inspect/issues/2).)

**Comment by iwehrman** [comment]
Assigning to @bchintx and marking Sprint 5.

**Comment by pthiess** [comment]
@bchintx Set priority to medium.

**Comment by bchintx** [comment]
pull request submitted to edge-code repo to merge this fix into Edge Code
https://git.corp.adobe.com/edge/edge-code/pull/200

**Comment by bchintx** [comment]
Fix confirmed in Edge Code master.  Closing...
