### ISSUE TITLE
[Core][Broken Link]:  Nothing happened when click the URLs on the Edge Inspect CC pane.

### ISSUE THREAD

**Issue by julieyuan** [edge-code/edge-inspect-extension#4]
Steps:
1. Launch Edge Code.
2. Click the Edge Inspect CC icon on the top right of Edge Code.
3. Click the link Get Edge Inspect CC on the Edge Inspect CC pane.
4. Install Edge Inspect app on OS and launch it.
5. Back to Edge Code and repeat step 2.
6. Click the link Upgrade.
7. Click the dropdown button which is behind Edge Inspect CC brand.
8. Click each URL for different devices in the dropdown list.

Results:
In step 3, step 6 and step 8, there is nothing happened. All the URLs don't redirect to any webpage.

Expected:
All the URLs should redirect to related webpage.

ENV: Win8 x86 , MAC 10.8.3 English OS
Build: 0.95.0-359080966

Notes: This issue also reproduces in latest Brackets build 0.28.0-8274

Snapshots:
Please refer to snapshots for details:
![222](https://f.cloud.github.com/assets/4251563/786605/df90581e-eabd-11e2-90e6-d496e528cd84.png)
![link1](https://f.cloud.github.com/assets/4251563/786600/79c7a294-eabd-11e2-9ea9-50372fecd22f.jpg)
![link11](https://f.cloud.github.com/assets/4251563/786598/79cc3264-eabd-11e2-98b8-e2ae21cfe5ca.png)

**Comment by iwehrman** [comment]
FBNC. Will be fixed once the EI extension is merged back in EC master. Back to @julieyuan to verify fixed once that happens.

**Comment by iwehrman** [comment]
Fixed in master. FBNC to @julieyuan.

**Comment by julieyuan** [comment]
Checked this issue in  Brackets build 0.28.0.8470. It is fixed. So close it. Please refer to snapshot:
![screen shot 2013-07-21 at 7 45 41 pm](https://f.cloud.github.com/assets/4251563/832858/4e997b3c-f27a-11e2-9a1f-970f481edfa2.png)
