### ISSUE TITLE
[L10N][Japanese]: Overlap for string "Edge Inspect CC for Android devices..." on the Edge Inspect CC pane.

### ISSUE THREAD

**Issue by julieyuan** [edge-code/edge-inspect-extension#7]
Steps:
1. Lanuch Brackets.
2. Install Edge inspect extension from URL: https://github.com/edge-code/edge-inspect-extension
3. Click the Inspect icon on the top right of the Brackets.
4. There will be a menu on the left of the icon
5. Click the dropdown button behind the string  Edge Inspect CC.  There will be a dropdown list.

Results:
There is overlap for string "Edge Inspect CC for Android devices..." on the Edge Inspect CC pane.

Expected:
All the strings should display well.

ENV: MAC 10.7.5 Japanese OS
Build: 0.28.0.8376

Snapshots:
Please refer to snapshots for details:
ENU:
![enu_edgecodep5_lk5_010_win8_28_8272](https://f.cloud.github.com/assets/4251563/817293/09d39e1e-ef6f-11e2-906b-3a1137887c3e.jpg)
JPN:
![inspect -extension](https://f.cloud.github.com/assets/4251563/817294/0a070510-ef6f-11e2-86c6-eea597f409e7.jpg)

**Comment by iwehrman** [comment]
See discussion in pull #9.

**Comment by iwehrman** [comment]
Fixed in master. FBNC to @julieyuan.

**Comment by julieyuan** [comment]
Checked this issue in Brackets build 0.28.0.8470. It is fixed. So close it. Please refer to snapshot:
![overlap](https://f.cloud.github.com/assets/4251563/832867/cb725d72-f27a-11e2-9fb2-e1be3fae14de.jpg)
