### ISSUE TITLE
[L10N][Japanese]: On and Off button should be localized on Edge Inspect CC pane.

### ISSUE THREAD

**Issue by julieyuan** [edge-code/edge-inspect-extension#8]
Steps:
1. Lanuch Brackets.
2. Install Edge inspect extension from URL: https://github.com/edge-code/edge-inspect-extension
3. Click the Inspect icon on the top right of the Brackets.

Result:
There is unlocalized button.

Expected:
On/Off button should be localized.Just same as Chrome Inspect extension.

Env: MAC 10.7.5 Japanese OS
Build: 0.28.0.8376

Snapshots:
Please refer to snapshots for details:
Edge Inspect CC pane:
![button-off and on-extensipn](https://f.cloud.github.com/assets/4251563/817408/01328172-ef73-11e2-895e-b2e3c203966d.jpg)
Chrome Inspect extension for reference
![button-off and on-chrome](https://f.cloud.github.com/assets/4251563/817409/0166b30c-ef73-11e2-8bef-8bfcb5f28824.jpg)

**Comment by iwehrman** [comment]
Fixed in master. FBNC to @julieyuan.

**Comment by julieyuan** [comment]
Checked this issue in Brackets build 0.28.0.8470. It is fixed. So close it. Please refer to snapshot:
![on-off button](https://f.cloud.github.com/assets/4251563/832861/8cbbbc68-f27a-11e2-9994-44488d3c2b0e.jpg)
